### ISSUE TITLE
all kubicctl commands throw rpc error

### ISSUE THREAD

**Issue by kruseio** [thkukuk/kubic-control#30]
Hello, just installed my kubic k8s cluster last week with 3 master nodes.
Now when i try to run any command against `kubicctl` the following error gets thrown:
```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0"
```

Everything is working fine as is with `kubectl`.
No errors to be found in `journalctl | grep kubicd`.

**Comment by APoniatowski** [comment]
having the same issue:
```
[HOSTNAME]:~ # kubicctl init --pod-network flannel --multi-master [LOADBALANCER-HOSTNAME.DNS]
Initializing kubernetes master can take several minutes, please be patient.
Could not initialize: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0"
```

Freshly installed opensuse kubic server (admin node) on proxmox

edit to add:

tried:
```
kubicctl init
```
and different variations, but the error is the same... seems like its a gRPC issue from googling this issue

**Comment by kruseio** [comment]
Not really a solution to this problem, but i am in a hurry so i redeployed and changed back to using `kubeadm`, to manage my nodes.

**Comment by APoniatowski** [comment]
I'm considering the same thing... I was hoping I can delegate it to kubicctl... but it seems like that won't happen  :(

@thkukuk to narrow down where the issue might be:
InitRequest in ```https://github.com/thkukuk/kubic-control/blob/master/api/api.proto```

and line 74 in ```https://github.com/thkukuk/kubic-control/blob/master/pkg/kubicctl/initMaster.go```
```
stream, err := client.InitMaster(ctx, &pb.InitRequest{PodNetworking: podNetwork, AdvAddr: adv_addr, ApiserverCertExtraSans: apiserver_cert_extra_sans, MultiMaster: multiMaster, KubernetesVersion: kubernetesVersion, Stage: stage, Haproxy: haproxy, FirstMaster: firstMaster})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Could not initialize: %v\n", err)
		return
	}
```

some of the methods are returning just an error or an actual return ```(&var/method/etc, error)```...  
not sure if this is intentional:
eg:
```func (s *kubeadm_server) InitMaster(in *pb.InitRequest, stream pb.Kubeadm_InitMasterServer) error { ... }```
and 
```func (s *kubeadm_server) RebootNode(ctx context.Context, in *pb.RebootNodeRequest) (*pb.StatusReply, error) { ... }```

meh... just grabbing at straws here, guessing... hopefully I set you on the right path  :)

**Comment by thkukuk** [comment]
> Not really a solution to this problem, but i am in a hurry so i redeployed and changed back to using `kubeadm`, to manage my nodes.

kubic-control is using kubeadm and is more or less stateless. So there is no need to redeploy with kubeadm, you can just continue to manage the cluster with kubeadm.

**Comment by thkukuk** [comment]
The problem are the certificates created by certstrap are no longer accepted by go1.15. Works fine until go1.14.

**Comment by kruseio** [comment]
> > Not really a solution to this problem, but i am in a hurry so i redeployed and changed back to using `kubeadm`, to manage my nodes.
> 
> kubic-control is using kubeadm and is more or less stateless. So there is no need to redeploy with kubeadm, you can just continue to manage the cluster with kubeadm.

That is good to know, but for my current project `kubeadm` does the trick.
But if you expect me to use `kubicctl` for my next project, it has to work every time.

> The problem are the certificates created by certstrap are no longer accepted by go1.15. Works fine until go1.14.

No offense but if a version change in Go breaks `kubicctl`, it indicates to me that the project is not totally stable. As such it may be good to inform newcomers as my self to this reality and label it as alpha or beta software accordingly.

**Comment by thkukuk** [comment]
> No offense but if a version change in Go breaks `kubicctl`, it indicates to me that the project is not totally stable. As such it may be good to inform newcomers as my self to this reality and label it as alpha or beta software accordingly.

Looks like you did not understand: the handling of certificates in go1.15 has changed incompatible and certificates generated by certstrap in the current way are not accepted anymore. If you did generate the certificates with something else or in a different way, kubicctl will continue to work. Neither certstrap nor the go compiler are part of the kubic-control project and the problem is not bound to kubicctl. If you google for it, you will find many big, very well known projects which did run into the same issue.
So the question is more if go itself is mature enough if they introduce such incompatible changes.
